### ISSUE TITLE
Docker run requires additional flag "--security-opt seccomp:unconfined" starting v1.10

### ISSUE THREAD

**Issue by vimgodfrey** [Ducatel/Visual-Studio-Linux-Build-Box#1]
Security Updated for Docker requires new launch flag
Errors:
gdbserver fails w/ "Cannot PTRACE_TRACEME: Operation not permitted"
VS2015 will error w/ "Cannot start gdbserver"

`docker run -d -p 12345:22 visual-studio-linux-build-box`
Should be updated to:
`docker run -d -p 12345:22  --security-opt seccomp:unconfined visual-studio-linux-build-box`

References: 
https://github.com/docker/docker/issues/20064
https://blog.docker.com/2016/02/docker-engine-1-10-security/

**Comment by Ducatel** [comment]
Hi @vimgodfrey ,

I will add this in the readme.
But I have no error with the docker 1.11. 
Which version did you use to generate this error ?

**Comment by vimgodfrey** [comment]
Docker version 1.12.0, build 8eab29e

**Comment by Ducatel** [comment]
OK, thanks.
