### ISSUE TITLE
Rebuild the image

### ISSUE THREAD

**Issue by bazzilic** [Ducatel/Visual-Studio-Linux-Build-Box#2]
Hi, thanks for putting this image out there, really helpful.

Would be nice if you could rebuild it to update to the latest ubuntu image and latest package versions 👍

**Comment by Ducatel** [comment]
Hi bazzilic,
I made some configuration to rebuild this image every week and after each push on the ubuntu base image in the docker hub ;)

So now, the image will be up to date automatically ;)
