### ISSUE TITLE
Port not exposed on host

### ISSUE THREAD

**Issue by JohanBerg78** [Ducatel/Visual-Studio-Linux-Build-Box#4]
Good day. Following the instructions as is results in port `12345` not being exposed on our Windows 10 x64 (Domain client, with DHCP enabled). How do we fix this? `netstat -a` on the host shows port `12345` not being used on any host interface. netstat within the ducatel container shows a binding to `0.0.0.0:22`. Thank you.

I also tried binding port `12345` to a specific interface (the ethernet adapter of the host) - this results in error :
```
$ docker run -d -p 192.168.100.176:12345:22 --security-opt seccomp:unconfined ducatel/visual-studio-linux-build-box
d4e6452c0d7156e3081197cab14ee4dba463e322c9fd6edbd0bccab2df498774
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint priceless_turing (88f3ca6c96931b88c0215a5ba5969144d674d6b3affe38253e54aa2d50492a06): Error starting userland proxy: listen tcp 192.168.100.176:12345: bind: cannot assign requested address.
```

**Comment by Ducatel** [comment]
Hi, 
Can you try with the version `16.04` like

```
C:\Users\me>docker run -d -p 12345:22 --security-opt seccomp:unconfined ducatel/visual-studio-linux-build-box:16.04
9ac6c430ede502418966323baa6956cc8227dd4fb56e25fe9ded5c83b36d4752

C:\Users\me>docker ps
CONTAINER ID        IMAGE                                         COMMAND               CREATED             STATUS              PORTS                   NAMES
9ac6c430ede5        ducatel/visual-studio-linux-build-box:16.04   "/usr/sbin/sshd -D"   5 seconds ago       Up 3 seconds        0.0.0.0:12345->22/tcp   elastic_dubinsky
```

**Comment by JohanBerg78** [comment]
Thank you for trying to help. A copy past from my docker toolbox terminal…

$ docker run -d -p 12345:22 --security-opt seccomp:unconfined ducatel/visual-studio-linux-build-box:16.04
Unable to find image 'ducatel/visual-studio-linux-build-box:16.04' locally
16.04: Pulling from ducatel/visual-studio-linux-build-box
297061f60c36: Pull complete
e9ccef17b516: Pull complete
dbc33716854d: Pull complete
8fe36b178d25: Pull complete
686596545a94: Pull complete
77c7747b7e54: Pull complete
Digest: sha256:f77f2e52a3177c5bdee79ab0fcf8b84eee2384c4cb355c2a94655b82bf6b7ffa
Status: Downloaded newer image for ducatel/visual-studio-linux-build-box:16.04
78d6e7b9250b7f548121c761f964424723cd323821fcdf14a171a968c39872b6

johan.hiden@hiden MINGW64 /c/Program Files/Docker Toolbox
$ docker ps -a
CONTAINER ID        IMAGE                                         COMMAND               CREATED             STATUS              PORTS                   NAMES
78d6e7b9250b        ducatel/visual-studio-linux-build-box:16.04   "/usr/sbin/sshd -D"   41 seconds ago      Up 34 seconds       0.0.0.0:12345->22/tcp   upbeat_hamilton

johan.hiden@hiden MINGW64 /c/Program Files/Docker Toolbox
$ netstat -a -n

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:623            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:3389           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:8192           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:8193           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:8194           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:16992          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:24780          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49668          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49669          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49673          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49681          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:51052          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:60574          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:3213         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:14726        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:15937        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49670        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49670        127.0.0.1:64430        ESTABLISHED
  TCP    127.0.0.1:49670        127.0.0.1:64848        ESTABLISHED
  TCP    127.0.0.1:49670        127.0.0.1:64853        ESTABLISHED
  TCP    127.0.0.1:49670        127.0.0.1:65229        ESTABLISHED
  TCP    127.0.0.1:49792        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:51399        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:59243        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:64430        127.0.0.1:49670        ESTABLISHED
  TCP    127.0.0.1:64848        127.0.0.1:49670        ESTABLISHED
  TCP    127.0.0.1:64853        127.0.0.1:49670        ESTABLISHED
  TCP    127.0.0.1:65229        127.0.0.1:49670        ESTABLISHED
  TCP    127.0.0.1:65334        127.0.0.1:65335        ESTABLISHED
  TCP    127.0.0.1:65335        127.0.0.1:65334        ESTABLISHED
  TCP    127.0.0.1:65352        127.0.0.1:65353        ESTABLISHED
  TCP    127.0.0.1:65353        127.0.0.1:65352        ESTABLISHED
  TCP    127.0.0.1:65355        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:65356        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:65356        127.0.0.1:65357        ESTABLISHED
  TCP    127.0.0.1:65357        127.0.0.1:65356        ESTABLISHED
  TCP    192.168.3.103:139      0.0.0.0:0              LISTENING
  TCP    192.168.3.103:8194     192.168.3.103:65354    ESTABLISHED
  TCP    192.168.3.103:65354    192.168.3.103:8194     ESTABLISHED
  TCP    192.168.56.1:139       0.0.0.0:0              LISTENING
  TCP    192.168.56.1:5040      0.0.0.0:0              LISTENING
  TCP    192.168.99.1:139       0.0.0.0:0              LISTENING
  TCP    192.168.99.1:5040      0.0.0.0:0              LISTENING
  TCP    192.168.99.1:24780     192.168.99.1:49697     ESTABLISHED
  TCP    192.168.99.1:49697     192.168.99.1:24780     ESTABLISHED
  TCP    192.168.100.176:80     0.0.0.0:0              LISTENING
  TCP    192.168.100.176:139    0.0.0.0:0              LISTENING
  TCP    192.168.100.176:443    0.0.0.0:0              LISTENING
  TCP    192.168.100.176:57220  0.0.0.0:0              LISTENING
  TCP    192.168.100.176:64339  13.92.209.232:443      ESTABLISHED
  TCP    192.168.100.176:64349  91.190.218.65:12350    ESTABLISHED
  TCP    192.168.100.176:64350  64.4.23.156:33033      ESTABLISHED
  TCP    192.168.100.176:64353  40.113.104.157:443     ESTABLISHED
  TCP    192.168.100.176:64354  52.114.74.38:443       ESTABLISHED
  TCP    192.168.100.176:64355  40.77.226.192:443      ESTABLISHED
  TCP    192.168.100.176:64360  13.92.209.232:443      ESTABLISHED
  TCP    192.168.100.176:64419  62.112.45.74:443       ESTABLISHED
  TCP    192.168.100.176:64431  52.86.181.127:443      ESTABLISHED
  TCP    192.168.100.176:64634  203.247.157.100:49002  CLOSE_WAIT
  TCP    192.168.100.176:64816  40.100.175.146:443     ESTABLISHED
  TCP    192.168.100.176:64849  64.233.167.188:5228    ESTABLISHED
  TCP    192.168.100.176:64850  138.91.237.237:443     ESTABLISHED
  TCP    192.168.100.176:64854  64.71.168.222:443      ESTABLISHED
  TCP    192.168.100.176:65064  52.114.74.43:443       ESTABLISHED
  TCP    192.168.100.176:65110  52.177.200.188:443     ESTABLISHED
  TCP    192.168.100.176:65178  40.100.173.2:443       ESTABLISHED
  TCP    192.168.100.176:65192  62.112.45.69:443       ESTABLISHED
  TCP    192.168.100.176:65197  52.97.131.162:443      ESTABLISHED
  TCP    192.168.100.176:65200  62.112.45.69:443       ESTABLISHED
  TCP    192.168.100.176:65230  54.174.16.18:443       ESTABLISHED
  TCP    192.168.100.176:65274  62.112.45.69:443       ESTABLISHED
  TCP    192.168.100.176:65358  62.112.45.69:443       ESTABLISHED
  TCP    192.168.100.176:65362  52.109.76.34:443       TIME_WAIT
  TCP    192.168.100.176:65364  62.112.45.72:24780     TIME_WAIT
  TCP    192.168.100.176:65366  40.100.173.242:443     ESTABLISHED
  TCP    192.168.100.176:65368  62.112.45.72:24780     TIME_WAIT
  TCP    [::]:135               [::]:0                 LISTENING
  TCP    [::]:445               [::]:0                 LISTENING
  TCP    [::]:623               [::]:0                 LISTENING
  TCP    [::]:3389              [::]:0                 LISTENING
  TCP    [::]:5357              [::]:0                 LISTENING
  TCP    [::]:7680              [::]:0                 LISTENING
  TCP    [::]:16992             [::]:0                 LISTENING
  TCP    [::]:24780             [::]:0                 LISTENING
  TCP    [::]:49664             [::]:0                 LISTENING
  TCP    [::]:49665             [::]:0                 LISTENING
  TCP    [::]:49666             [::]:0                 LISTENING
  TCP    [::]:49667             [::]:0                 LISTENING
  TCP    [::]:49668             [::]:0                 LISTENING
  TCP    [::]:49669             [::]:0                 LISTENING
  TCP    [::]:49673             [::]:0                 LISTENING
  TCP    [::]:49681             [::]:0                 LISTENING
  TCP    [::]:51052             [::]:0                 LISTENING
  TCP    [::]:60574             [::]:0                 LISTENING
  TCP    [::1]:49790            [::]:0                 LISTENING
  TCP    [::1]:62276            [::1]:62278            ESTABLISHED
  TCP    [::1]:62278            [::1]:62276            ESTABLISHED

**Comment by Ducatel** [comment]
So as you can see the port mapping is well done
```
0.0.0.0:12345->22/tcp
```

Can you check your docker version ?
```
docker --version
```

Can you try to connect on container with [Putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)
![image](https://user-images.githubusercontent.com/1184332/40711419-6716012e-63fb-11e8-87e7-9f69c5bfd8a1.png)

**Comment by JohanBerg78** [comment]
I tried with “localhost”, “hostname(hiden)”, and “127.0.0.1” all fail with the same result “Connection refused”.
I also disabled the windows defender firewall temporary – it made no difference for me.

Could this be because I also have (the very latest for today) VirtualBox installed? I will try a clean install of docker tools on another host, or with the Hyper-V Docker and send feedback soon.

(Thanks for  the support so far).

**Comment by Ducatel** [comment]
Check your docker version.
I think I remember that docker toolbox was deprecated.

**Comment by JohanBerg78** [comment]
Hyper-V version of Docker solves the problem (with non-related to this ticket side effects, I will mention for background).

1)      Hyper-V version only works on Windows 10, and Server 2016 at this time.

2)      VirtualBox cannot be installed on the same host.

Thank you for the help, I presume this is the final state at this time.
Johan.

**Comment by Ducatel** [comment]
>  2) VirtualBox cannot be installed on the same host.
It's the same problem with VMware ...

So it's fine for me :D
