### ISSUE TITLE
Host name

### ISSUE THREAD

**Issue by srashee** [Ducatel/Visual-Studio-Linux-Build-Box#7]
In the README i'd reccomend saying to use localhost instead of docker container hostname.

I can fork and update if you find this reasonable.

**Comment by Ducatel** [comment]
Hi,

I wrote the command line for an external linux host. So it cannot be localhost.
Bu maybe we can add a command line for docker windows

**Comment by srashee** [comment]
I realized it says docker host.. implying the host running the docker daemon. I believe that should be sufficient and I was just misreading.

Apologies.
