### ISSUE TITLE
password not correct?

### ISSUE THREAD

**Issue by Anda001** [Ducatel/Visual-Studio-Linux-Build-Box#8]
it seems can't login

**Comment by Ducatel** [comment]
Hi,

You should add some detail on your error. 
Like that, I cannot help you, I'm not a magician :laughing:

**Comment by Anda001** [comment]
tks for response.
for my poor English. we let the image talk.

![image](https://user-images.githubusercontent.com/1329895/71637584-6da2a380-2c81-11ea-8f22-eef6c768d0eb.png)

**Comment by Anda001** [comment]
by the way, I'm on windows 10 platform as docker host.

**Comment by Ducatel** [comment]
So I have tested on windows 10 host and it's working perfectly.
![image](https://user-images.githubusercontent.com/1184332/71660193-8fb42880-2d4a-11ea-95d0-756273deab36.png)

Maybe the error come from your ssh client. Check directly in cmd with the default windows ssh client.

**Comment by Anda001** [comment]
no. it's the image's problem.
I tried the image " bryanayers/visual-studio-linux-build-box", it works OK,although it didn't get many stars.
